### ISSUE TITLE
Add New Dialect: Polish (Python)

### ISSUE THREAD

**Issue by tomekp97** [legesher/legesher-translations#14]
Hiya! This project seems like an excellent idea and a brilliant way of teaching people to program!
If you think adding a Polish localisation would be useful, I'd be happy to help. :+1:

**Comment by madiedgar** [comment]
That would be amazing @tomekp97! That's exactly our heart behind what we do 😄. Here are some instructions on how to add Polish to this repository. 

## Adding Polish to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create polish dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `polish-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

**Comment by tomekp97** [comment]
Heya! So, I've finished the Polish translations for Python :tada: - this was a really fun thing to work on!

Couple of small things:

1) Can I get you to create a `polish-translation` branch that I can PR to, please?

2) I wasn't sure if I missed something during the forking/cloning but there wasn't a `locale` directory in my fork ([steps 1 & 2 of the translation guide](https://legesher.readme.io/docs/translation-guide#section-1-confirm-language-abbreviation)) or a [bootstrapping script](https://github.com/legesher/legesher-translations/blob/master/README.md#installation).
So I used the structure of the `master` branch and tried to follow @ZeroOne010101 in the way the translations are commented and whatnot.

**Comment by madiedgar** [comment]
Thank you so much @tomekp97 for this! I created the `polish-translation` branch for you and merged my branch with the `locale/` folder. 👍

**Comment by madiedgar** [comment]
Great job @tomekp97, I'm closing this issue as this was resolved in #21. I'll open up a translation review issue so we can merge in this wonderful work for people to use 👍
