### ISSUE TITLE
Add new Dialect: French(Python)

### ISSUE THREAD

**Issue by wang-ories** [legesher/legesher-translations#17]
Hello @madiedgar, I would like to contribute with french translation if needed.

**Comment by madiedgar** [comment]
Hey @wang-ories 👋! This would be absolutely amazing!! Here's some information on where to start!

## Adding French to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create german dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `french-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

**Comment by wang-ories** [comment]
Ok @madiedgar, 
Of course I want to be one of the reviewers for the french language.

**Comment by madiedgar** [comment]
Awesome! Thanks @wang-ories! Would you like to help start us out in French by walking through the translation guide to add a French yml file and translations for the Python programming language? I created the `french-translation` branch to merge the changes into via PR. 😄

**Comment by wang-ories** [comment]
> Awesome! Thanks @wang-ories! Would you like to help start us out in French by walking through the translation guide to add a French yml file and translations for the Python programming language? I created the `french-translation` branch to merge the changes into via PR. 😄

Ok @madiedgar

**Comment by madiedgar** [comment]
Great job @wang-ories, I'm closing this issue as this was resolved in #22. I'll open up a translation review issue so we can merge in this wonderful work for people to use 👍
