### ISSUE TITLE
Add New Dialect: Italian (Python)

### ISSUE THREAD

**Issue by ninoCan** [legesher/legesher-translations#24]
Hello @madiedgar, I noticed that italian is missing amongst the languages, I would like to contribute in this way

**Comment by madiedgar** [comment]
Absolutely @ninoCan!! That would be amazing 😄 Here are some details to add a new dialect.

## Adding Italian to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

**To complete this issue**:
- [ ] Create Italian dialect `.yml` file
- [ ] Enter translation for _at least_ the Python keywords
- [ ] Merge changes into branch titled `italian-translation` on this repo

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

**Comment by madiedgar** [comment]
Great job @ninoCan, I'm closing this issue as this was resolved in #25 & #26. I'll open up a translation review issue so we can merge in this wonderful work for people to use 👍
